apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe-health-check
spec:
  host: cafe.example.com
  tls:
    secret: cafe-secret
  upstreams:
  - name: tea
    service: tea-svc
    port: 80
    healthCheck:
      enable: true
      path: /healthz
      interval: 5s
      fails: 3
      passes: 1
      port: 80
      statusMatch: "200"
  - name: coffee
    service: coffee-svc
    port: 80
  routes:
  - path: /tea
    action:
      pass: tea
  - path: /coffee
    action:
      pass: coffee
