apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress-master
  annotations:
    kubernetes.io/ingress.class: "nginx-plus"
    nginx.org/mergeable-ingress-type: "master"
spec:
  rules:
  - host: cafe.example.com
