kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  http-snippets: |
    keyval_zone zone=limitreq_uri:64k;
    keyval $uri $enablelimit zone=limitreq_uri;

    map $enablelimit $limit_key {
      default "";
      1  $binary_remote_addr;
    }

    limit_req_zone $limit_key zone=req_10:1m rate=10r/s;
    limit_req_zone $limit_key zone=req_20:1m rate=20r/s;

    server {
        listen 9000;

        root /usr/share/nginx/html;

        access_log off;

        allow 10.1.10.0/24;

        deny all;
        location /api {
            api write=on;
        }
    }
