apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: secure-cafe
spec:
  listener:
    name: tls-passthrough
    protocol: TLS_PASSTHROUGH
  host: cafe.example.com
  upstreams:
    - name: secure-cafe
      service: secure-cafe
      port: 8443
  action:
    pass: secure-cafe
